#############################################################################
# Makefile for building: ../bin/data_element
# Generated by qmake (2.01a) (Qt 4.6.3) on: Wed Mar 16 16:40:49 2011
# Project:  src.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++-64 -unix -o Makefile src.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -m64 -pipe -O2 -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -D_REENTRANT -Wall -W $(DEFINES)
CXXFLAGS      = -m64 -pipe -O2 -fmessage-length=0 -O2 -Wall -D_FORTIFY_SOURCE=2 -fstack-protector -funwind-tables -fasynchronous-unwind-tables -g -D_REENTRANT -Wall -W $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++-64 -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I. -I/usr/include/qwt -I.
LINK          = g++
LFLAGS        = -m64 -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib64 -lqwt -lcln -lginac -lQtGui -L/usr/lib64 -L/usr/X11R6/lib64 -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		specdataitem.cpp \
		specmodel.cpp \
		specdescriptordelegate.cpp \
		specmodelitem.cpp \
		specplotwidget.cpp \
		utility-functions.cpp \
		specappwindow.cpp \
		specdelegate.cpp \
		specview.cpp \
		specdatapoint.cpp \
		specdescriptor.cpp \
		specdocktitle.cpp \
		canvaspicker.cpp \
		speczoomer.cpp \
		specplot.cpp \
		speclabeldialog.cpp \
		specrange.cpp \
		specminmaxvalidator.cpp \
		speckineticwidget.cpp \
		speckinetic.cpp \
		specfolderitem.cpp \
		speclogentryitem.cpp \
		speccanvasitem.cpp \
		exportdialog.cpp \
		exportlayoutitem.cpp \
		exportformatitem.cpp \
		speclogmessage.cpp \
		specdataview.cpp \
		speckineticview.cpp \
		speckineticmodel.cpp \
		speckineticrange.cpp \
		speckrcontextmenu.cpp \
		cutbyintensitydialog.cpp moc_specmodel.cpp \
		moc_specplotwidget.cpp \
		moc_specappwindow.cpp \
		moc_specdelegate.cpp \
		moc_specview.cpp \
		moc_specdocktitle.cpp \
		moc_canvaspicker.cpp \
		moc_specplot.cpp \
		moc_speclabeldialog.cpp \
		moc_specminmaxvalidator.cpp \
		moc_speckineticwidget.cpp \
		moc_exportdialog.cpp \
		moc_exportlayoutitem.cpp \
		moc_exportformatitem.cpp \
		moc_specdataview.cpp \
		moc_speckineticview.cpp \
		moc_speckineticmodel.cpp \
		moc_speckrcontextmenu.cpp \
		moc_cutbyintensitydialog.cpp \
		qrc_application.cpp
OBJECTS       = main.o \
		specdataitem.o \
		specmodel.o \
		specdescriptordelegate.o \
		specmodelitem.o \
		specplotwidget.o \
		utility-functions.o \
		specappwindow.o \
		specdelegate.o \
		specview.o \
		specdatapoint.o \
		specdescriptor.o \
		specdocktitle.o \
		canvaspicker.o \
		speczoomer.o \
		specplot.o \
		speclabeldialog.o \
		specrange.o \
		specminmaxvalidator.o \
		speckineticwidget.o \
		speckinetic.o \
		specfolderitem.o \
		speclogentryitem.o \
		speccanvasitem.o \
		exportdialog.o \
		exportlayoutitem.o \
		exportformatitem.o \
		speclogmessage.o \
		specdataview.o \
		speckineticview.o \
		speckineticmodel.o \
		speckineticrange.o \
		speckrcontextmenu.o \
		cutbyintensitydialog.o \
		moc_specmodel.o \
		moc_specplotwidget.o \
		moc_specappwindow.o \
		moc_specdelegate.o \
		moc_specview.o \
		moc_specdocktitle.o \
		moc_canvaspicker.o \
		moc_specplot.o \
		moc_speclabeldialog.o \
		moc_specminmaxvalidator.o \
		moc_speckineticwidget.o \
		moc_exportdialog.o \
		moc_exportlayoutitem.o \
		moc_exportformatitem.o \
		moc_specdataview.o \
		moc_speckineticview.o \
		moc_speckineticmodel.o \
		moc_speckrcontextmenu.o \
		moc_cutbyintensitydialog.o \
		qrc_application.o
DIST          = /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		src.pro
QMAKE_TARGET  = data_element
DESTDIR       = ../bin/
TARGET        = ../bin/data_element

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	@$(CHK_DIR_EXISTS) ../bin/ || $(MKDIR) ../bin/ 
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: src.pro  /usr/share/qt4/mkspecs/linux-g++-64/qmake.conf /usr/share/qt4/mkspecs/common/g++.conf \
		/usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -unix -o Makefile src.pro
/usr/share/qt4/mkspecs/common/g++.conf:
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++-64 -unix -o Makefile src.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/data_element1.0.0 || $(MKDIR) .tmp/data_element1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/data_element1.0.0/ && $(COPY_FILE) --parents specdataitem.h specmodel.h specdescriptordelegate.h specmodelitem.h specplotwidget.h utility-functions.h specappwindow.h specdelegate.h specview.h specdatapoint.h specdescriptor.h specdocktitle.h canvaspicker.h names.h speczoomer.h specplot.h speclabeldialog.h specrange.h specminmaxvalidator.h speckineticwidget.h speckinetic.h specfolderitem.h speclogentryitem.h speccanvasitem.h exportdialog.h exportlayoutitem.h exportformatitem.h speclogmessage.h specdataview.h speckineticview.h speckineticmodel.h speckineticrange.h speckrcontextmenu.h cutbyintensitydialog.h .tmp/data_element1.0.0/ && $(COPY_FILE) --parents application.qrc .tmp/data_element1.0.0/ && $(COPY_FILE) --parents main.cpp specdataitem.cpp specmodel.cpp specdescriptordelegate.cpp specmodelitem.cpp specplotwidget.cpp utility-functions.cpp specappwindow.cpp specdelegate.cpp specview.cpp specdatapoint.cpp specdescriptor.cpp specdocktitle.cpp canvaspicker.cpp speczoomer.cpp specplot.cpp speclabeldialog.cpp specrange.cpp specminmaxvalidator.cpp speckineticwidget.cpp speckinetic.cpp specfolderitem.cpp speclogentryitem.cpp speccanvasitem.cpp exportdialog.cpp exportlayoutitem.cpp exportformatitem.cpp speclogmessage.cpp specdataview.cpp speckineticview.cpp speckineticmodel.cpp speckineticrange.cpp speckrcontextmenu.cpp cutbyintensitydialog.cpp .tmp/data_element1.0.0/ && (cd `dirname .tmp/data_element1.0.0` && $(TAR) data_element1.0.0.tar data_element1.0.0 && $(COMPRESS) data_element1.0.0.tar) && $(MOVE) `dirname .tmp/data_element1.0.0`/data_element1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/data_element1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_specmodel.cpp moc_specplotwidget.cpp moc_specappwindow.cpp moc_specdelegate.cpp moc_specview.cpp moc_specdocktitle.cpp moc_canvaspicker.cpp moc_specplot.cpp moc_speclabeldialog.cpp moc_specminmaxvalidator.cpp moc_speckineticwidget.cpp moc_exportdialog.cpp moc_exportlayoutitem.cpp moc_exportformatitem.cpp moc_specdataview.cpp moc_speckineticview.cpp moc_speckineticmodel.cpp moc_speckrcontextmenu.cpp moc_cutbyintensitydialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_specmodel.cpp moc_specplotwidget.cpp moc_specappwindow.cpp moc_specdelegate.cpp moc_specview.cpp moc_specdocktitle.cpp moc_canvaspicker.cpp moc_specplot.cpp moc_speclabeldialog.cpp moc_specminmaxvalidator.cpp moc_speckineticwidget.cpp moc_exportdialog.cpp moc_exportlayoutitem.cpp moc_exportformatitem.cpp moc_specdataview.cpp moc_speckineticview.cpp moc_speckineticmodel.cpp moc_speckrcontextmenu.cpp moc_cutbyintensitydialog.cpp
moc_specmodel.cpp: specfolderitem.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		specdataitem.h \
		specdatapoint.h \
		specdescriptor.h \
		specmodel.h
	/usr/bin/moc $(DEFINES) $(INCPATH) specmodel.h -o moc_specmodel.cpp

moc_specplotwidget.cpp: specplot.h \
		canvaspicker.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		speczoomer.h \
		specdataview.h \
		specview.h \
		specmodel.h \
		specfolderitem.h \
		specdataitem.h \
		specdatapoint.h \
		specdescriptor.h \
		specdocktitle.h \
		speckineticwidget.h \
		speckinetic.h \
		speckineticview.h \
		speckineticmodel.h \
		specplotwidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) specplotwidget.h -o moc_specplotwidget.cpp

moc_specappwindow.cpp: specplotwidget.h \
		specplot.h \
		canvaspicker.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		speczoomer.h \
		specdataview.h \
		specview.h \
		specmodel.h \
		specfolderitem.h \
		specdataitem.h \
		specdatapoint.h \
		specdescriptor.h \
		specdocktitle.h \
		speckineticwidget.h \
		speckinetic.h \
		speckineticview.h \
		speckineticmodel.h \
		specappwindow.h
	/usr/bin/moc $(DEFINES) $(INCPATH) specappwindow.h -o moc_specappwindow.cpp

moc_specdelegate.cpp: specdelegate.h
	/usr/bin/moc $(DEFINES) $(INCPATH) specdelegate.h -o moc_specdelegate.cpp

moc_specview.cpp: specmodel.h \
		specfolderitem.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		specdataitem.h \
		specdatapoint.h \
		specdescriptor.h \
		specview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) specview.h -o moc_specview.cpp

moc_specdocktitle.cpp: specdocktitle.h
	/usr/bin/moc $(DEFINES) $(INCPATH) specdocktitle.h -o moc_specdocktitle.cpp

moc_canvaspicker.cpp: specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		canvaspicker.h
	/usr/bin/moc $(DEFINES) $(INCPATH) canvaspicker.h -o moc_canvaspicker.cpp

moc_specplot.cpp: canvaspicker.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		speczoomer.h \
		specplot.h
	/usr/bin/moc $(DEFINES) $(INCPATH) specplot.h -o moc_specplot.cpp

moc_speclabeldialog.cpp: speclabeldialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) speclabeldialog.h -o moc_speclabeldialog.cpp

moc_specminmaxvalidator.cpp: specminmaxvalidator.h
	/usr/bin/moc $(DEFINES) $(INCPATH) specminmaxvalidator.h -o moc_specminmaxvalidator.cpp

moc_speckineticwidget.cpp: speckinetic.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		specmodel.h \
		specfolderitem.h \
		specdataitem.h \
		specdatapoint.h \
		specdescriptor.h \
		specplot.h \
		canvaspicker.h \
		speczoomer.h \
		speckineticview.h \
		specview.h \
		speckineticmodel.h \
		speckineticwidget.h
	/usr/bin/moc $(DEFINES) $(INCPATH) speckineticwidget.h -o moc_speckineticwidget.cpp

moc_exportdialog.cpp: exportlayoutitem.h \
		exportformatitem.h \
		names.h \
		exportdialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) exportdialog.h -o moc_exportdialog.cpp

moc_exportlayoutitem.cpp: exportlayoutitem.h
	/usr/bin/moc $(DEFINES) $(INCPATH) exportlayoutitem.h -o moc_exportlayoutitem.cpp

moc_exportformatitem.cpp: names.h \
		exportformatitem.h
	/usr/bin/moc $(DEFINES) $(INCPATH) exportformatitem.h -o moc_exportformatitem.cpp

moc_specdataview.cpp: specview.h \
		specmodel.h \
		specfolderitem.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		specdataitem.h \
		specdatapoint.h \
		specdescriptor.h \
		specdataview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) specdataview.h -o moc_specdataview.cpp

moc_speckineticview.cpp: specview.h \
		specmodel.h \
		specfolderitem.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		specdataitem.h \
		specdatapoint.h \
		specdescriptor.h \
		speckineticmodel.h \
		speckineticview.h
	/usr/bin/moc $(DEFINES) $(INCPATH) speckineticview.h -o moc_speckineticview.cpp

moc_speckineticmodel.cpp: specmodel.h \
		specfolderitem.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		specdataitem.h \
		specdatapoint.h \
		specdescriptor.h \
		speckineticmodel.h
	/usr/bin/moc $(DEFINES) $(INCPATH) speckineticmodel.h -o moc_speckineticmodel.cpp

moc_speckrcontextmenu.cpp: speccanvasitem.h \
		names.h \
		speckrcontextmenu.h
	/usr/bin/moc $(DEFINES) $(INCPATH) speckrcontextmenu.h -o moc_speckrcontextmenu.cpp

moc_cutbyintensitydialog.cpp: specplot.h \
		canvaspicker.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		speczoomer.h \
		cutbyintensitydialog.h
	/usr/bin/moc $(DEFINES) $(INCPATH) cutbyintensitydialog.h -o moc_cutbyintensitydialog.cpp

compiler_rcc_make_all: qrc_application.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_application.cpp
qrc_application.cpp: application.qrc \
		individualZero.png \
		folder.png \
		toKinetic.png \
		folder_new.png \
		lineWidth.png \
		filenew.png \
		addZeroRange.png \
		data.png \
		mave.png \
		fromKinetic.png \
		filesaveas.png \
		cbi.png \
		newrange.png \
		color.png \
		merge2.png \
		zeroCorrection.png \
		item_delete.png \
		deleteZeroRange.png \
		merge.png \
		remove.png \
		close_dock.png \
		fileimport.png \
		multiaction.png \
		fileopen.png \
		sys_message.png \
		filesave.png \
		changeylabel.png \
		offset.png \
		export.png \
		kineticwindow.png \
		merge_folder.png \
		scale.png \
		add.png \
		log_message.png \
		changetitle.png \
		changexlabel.png \
		kinetic.png \
		float_dock.png \
		tree.png \
		ave.png \
		offline.png
	/usr/bin/rcc -name application application.qrc -o qrc_application.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

main.o: main.cpp specappwindow.h \
		specplotwidget.h \
		specplot.h \
		canvaspicker.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		speczoomer.h \
		specdataview.h \
		specview.h \
		specmodel.h \
		specfolderitem.h \
		specdataitem.h \
		specdatapoint.h \
		specdescriptor.h \
		specdocktitle.h \
		speckineticwidget.h \
		speckinetic.h \
		speckineticview.h \
		speckineticmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

specdataitem.o: specdataitem.cpp specdataitem.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		specdatapoint.h \
		specdescriptor.h \
		speckineticrange.h \
		speckinetic.h \
		specmodel.h \
		specfolderitem.h \
		specplot.h \
		canvaspicker.h \
		speczoomer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o specdataitem.o specdataitem.cpp

specmodel.o: specmodel.cpp specmodel.h \
		specfolderitem.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		specdataitem.h \
		specdatapoint.h \
		specdescriptor.h \
		utility-functions.h \
		exportdialog.h \
		exportlayoutitem.h \
		exportformatitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o specmodel.o specmodel.cpp

specdescriptordelegate.o: specdescriptordelegate.cpp specdescriptordelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o specdescriptordelegate.o specdescriptordelegate.cpp

specmodelitem.o: specmodelitem.cpp specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		specfolderitem.h \
		specdataitem.h \
		specdatapoint.h \
		specdescriptor.h \
		speclogentryitem.h \
		speclogmessage.h \
		speckinetic.h \
		specmodel.h \
		specplot.h \
		canvaspicker.h \
		speczoomer.h \
		speckineticrange.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o specmodelitem.o specmodelitem.cpp

specplotwidget.o: specplotwidget.cpp specplotwidget.h \
		specplot.h \
		canvaspicker.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		speczoomer.h \
		specdataview.h \
		specview.h \
		specmodel.h \
		specfolderitem.h \
		specdataitem.h \
		specdatapoint.h \
		specdescriptor.h \
		specdocktitle.h \
		speckineticwidget.h \
		speckinetic.h \
		speckineticview.h \
		speckineticmodel.h \
		utility-functions.h \
		specdelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o specplotwidget.o specplotwidget.cpp

utility-functions.o: utility-functions.cpp utility-functions.h \
		specdataitem.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		specdatapoint.h \
		specdescriptor.h \
		speclogentryitem.h \
		specfolderitem.h \
		speclogmessage.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o utility-functions.o utility-functions.cpp

specappwindow.o: specappwindow.cpp specappwindow.h \
		specplotwidget.h \
		specplot.h \
		canvaspicker.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		speczoomer.h \
		specdataview.h \
		specview.h \
		specmodel.h \
		specfolderitem.h \
		specdataitem.h \
		specdatapoint.h \
		specdescriptor.h \
		specdocktitle.h \
		speckineticwidget.h \
		speckinetic.h \
		speckineticview.h \
		speckineticmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o specappwindow.o specappwindow.cpp

specdelegate.o: specdelegate.cpp specdelegate.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o specdelegate.o specdelegate.cpp

specview.o: specview.cpp specview.h \
		specmodel.h \
		specfolderitem.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		specdataitem.h \
		specdatapoint.h \
		specdescriptor.h \
		specdelegate.h \
		cutbyintensitydialog.h \
		specplot.h \
		canvaspicker.h \
		speczoomer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o specview.o specview.cpp

specdatapoint.o: specdatapoint.cpp specdatapoint.h \
		names.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o specdatapoint.o specdatapoint.cpp

specdescriptor.o: specdescriptor.cpp specdescriptor.h \
		names.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o specdescriptor.o specdescriptor.cpp

specdocktitle.o: specdocktitle.cpp specdocktitle.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o specdocktitle.o specdocktitle.cpp

canvaspicker.o: canvaspicker.cpp specplot.h \
		canvaspicker.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		speczoomer.h \
		specminmaxvalidator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o canvaspicker.o canvaspicker.cpp

speczoomer.o: speczoomer.cpp speczoomer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o speczoomer.o speczoomer.cpp

specplot.o: specplot.cpp specplot.h \
		canvaspicker.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		speczoomer.h \
		speclabeldialog.h \
		speckineticrange.h \
		speckinetic.h \
		specmodel.h \
		specfolderitem.h \
		specdataitem.h \
		specdatapoint.h \
		specdescriptor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o specplot.o specplot.cpp

speclabeldialog.o: speclabeldialog.cpp speclabeldialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o speclabeldialog.o speclabeldialog.cpp

specrange.o: specrange.cpp specrange.h \
		speccanvasitem.h \
		names.h \
		specplot.h \
		canvaspicker.h \
		specmodelitem.h \
		speczoomer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o specrange.o specrange.cpp

specminmaxvalidator.o: specminmaxvalidator.cpp specminmaxvalidator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o specminmaxvalidator.o specminmaxvalidator.cpp

speckineticwidget.o: speckineticwidget.cpp speckineticwidget.h \
		speckinetic.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		specmodel.h \
		specfolderitem.h \
		specdataitem.h \
		specdatapoint.h \
		specdescriptor.h \
		specplot.h \
		canvaspicker.h \
		speczoomer.h \
		speckineticview.h \
		specview.h \
		speckineticmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o speckineticwidget.o speckineticwidget.cpp

speckinetic.o: speckinetic.cpp speckinetic.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		specmodel.h \
		specfolderitem.h \
		specdataitem.h \
		specdatapoint.h \
		specdescriptor.h \
		specplot.h \
		canvaspicker.h \
		speczoomer.h \
		speckineticrange.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o speckinetic.o speckinetic.cpp

specfolderitem.o: specfolderitem.cpp specfolderitem.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o specfolderitem.o specfolderitem.cpp

speclogentryitem.o: speclogentryitem.cpp speclogentryitem.h \
		specfolderitem.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		specdescriptor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o speclogentryitem.o speclogentryitem.cpp

speccanvasitem.o: speccanvasitem.cpp speccanvasitem.h \
		names.h \
		utility-functions.h \
		specdataitem.h \
		specmodelitem.h \
		specrange.h \
		specdatapoint.h \
		specdescriptor.h \
		specplot.h \
		canvaspicker.h \
		speczoomer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o speccanvasitem.o speccanvasitem.cpp

exportdialog.o: exportdialog.cpp exportdialog.h \
		exportlayoutitem.h \
		exportformatitem.h \
		names.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exportdialog.o exportdialog.cpp

exportlayoutitem.o: exportlayoutitem.cpp exportlayoutitem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exportlayoutitem.o exportlayoutitem.cpp

exportformatitem.o: exportformatitem.cpp exportformatitem.h \
		names.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o exportformatitem.o exportformatitem.cpp

speclogmessage.o: speclogmessage.cpp speclogmessage.h \
		specdataitem.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		specdatapoint.h \
		specdescriptor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o speclogmessage.o speclogmessage.cpp

specdataview.o: specdataview.cpp specdataview.h \
		specview.h \
		specmodel.h \
		specfolderitem.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		specdataitem.h \
		specdatapoint.h \
		specdescriptor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o specdataview.o specdataview.cpp

speckineticview.o: speckineticview.cpp speckineticview.h \
		specview.h \
		specmodel.h \
		specfolderitem.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		specdataitem.h \
		specdatapoint.h \
		specdescriptor.h \
		speckineticmodel.h \
		speckinetic.h \
		specplot.h \
		canvaspicker.h \
		speczoomer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o speckineticview.o speckineticview.cpp

speckineticmodel.o: speckineticmodel.cpp speckineticmodel.h \
		specmodel.h \
		specfolderitem.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		specdataitem.h \
		specdatapoint.h \
		specdescriptor.h \
		speckinetic.h \
		specplot.h \
		canvaspicker.h \
		speczoomer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o speckineticmodel.o speckineticmodel.cpp

speckineticrange.o: speckineticrange.cpp speckineticrange.h \
		specrange.h \
		speccanvasitem.h \
		names.h \
		speckinetic.h \
		specmodelitem.h \
		specmodel.h \
		specfolderitem.h \
		specdataitem.h \
		specdatapoint.h \
		specdescriptor.h \
		specplot.h \
		canvaspicker.h \
		speczoomer.h \
		speckrcontextmenu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o speckineticrange.o speckineticrange.cpp

speckrcontextmenu.o: speckrcontextmenu.cpp speckrcontextmenu.h \
		speccanvasitem.h \
		names.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o speckrcontextmenu.o speckrcontextmenu.cpp

cutbyintensitydialog.o: cutbyintensitydialog.cpp cutbyintensitydialog.h \
		specplot.h \
		canvaspicker.h \
		specmodelitem.h \
		speccanvasitem.h \
		names.h \
		specrange.h \
		speczoomer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cutbyintensitydialog.o cutbyintensitydialog.cpp

moc_specmodel.o: moc_specmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_specmodel.o moc_specmodel.cpp

moc_specplotwidget.o: moc_specplotwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_specplotwidget.o moc_specplotwidget.cpp

moc_specappwindow.o: moc_specappwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_specappwindow.o moc_specappwindow.cpp

moc_specdelegate.o: moc_specdelegate.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_specdelegate.o moc_specdelegate.cpp

moc_specview.o: moc_specview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_specview.o moc_specview.cpp

moc_specdocktitle.o: moc_specdocktitle.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_specdocktitle.o moc_specdocktitle.cpp

moc_canvaspicker.o: moc_canvaspicker.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_canvaspicker.o moc_canvaspicker.cpp

moc_specplot.o: moc_specplot.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_specplot.o moc_specplot.cpp

moc_speclabeldialog.o: moc_speclabeldialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_speclabeldialog.o moc_speclabeldialog.cpp

moc_specminmaxvalidator.o: moc_specminmaxvalidator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_specminmaxvalidator.o moc_specminmaxvalidator.cpp

moc_speckineticwidget.o: moc_speckineticwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_speckineticwidget.o moc_speckineticwidget.cpp

moc_exportdialog.o: moc_exportdialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_exportdialog.o moc_exportdialog.cpp

moc_exportlayoutitem.o: moc_exportlayoutitem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_exportlayoutitem.o moc_exportlayoutitem.cpp

moc_exportformatitem.o: moc_exportformatitem.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_exportformatitem.o moc_exportformatitem.cpp

moc_specdataview.o: moc_specdataview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_specdataview.o moc_specdataview.cpp

moc_speckineticview.o: moc_speckineticview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_speckineticview.o moc_speckineticview.cpp

moc_speckineticmodel.o: moc_speckineticmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_speckineticmodel.o moc_speckineticmodel.cpp

moc_speckrcontextmenu.o: moc_speckrcontextmenu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_speckrcontextmenu.o moc_speckrcontextmenu.cpp

moc_cutbyintensitydialog.o: moc_cutbyintensitydialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cutbyintensitydialog.o moc_cutbyintensitydialog.cpp

qrc_application.o: qrc_application.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_application.o qrc_application.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

